# Change these first
owner: Grandpurs45 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Cycleboss45
    url: https://cycleboss45.fr/
    statusPageUrl: https://grandpurs45.github.io/upptime
    method: GET
    maxResponseTime: 2000
    followRedirects: true
    icon: heart
    type: globalping
    location: france
    assignees:
      - grandpurs45

  - name: VerifApp - BO
    url: http://verifapp.duckdns.org:8080/index.php?controller=manager_auth&action=login_form
    statusPageUrl: https://grandpurs45.github.io/upptime
    method: GET
    maxResponseTime: 2000
    followRedirects: true
    icon: heart
    type: globalping
    location: france
    assignees:
      - grandpurs45

   - name: VerifApp - INGRE - Sortie pharmacie
    url: http://verifapp.duckdns.org:8080/index.php?controller=pharmacy&action=form
    statusPageUrl: https://grandpurs45.github.io/upptime
    method: GET
    maxResponseTime: 2000
    followRedirects: true
    icon: heart
    type: globalping
    location: france
    assignees:
      - grandpurs45

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Statut des services Grandpurs45**"
  introMessage: Suivi en temps réel de la disponibilité de mes services et applications.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
